### ISSUE TITLE
Create Order Relation Model

### ISSUE THREAD

**Issue by tichnas** [Domino-Developers/Larena-Backend#5]
Create the model with all attributes in `/backend/models.py`

- `user`* (FK to User)
- `product`* (FK to Product)
- `qty` (int, default = 1)
- `status` (enum- `ordered`, `out for delivery`, `delivered`)

Note:
- `*` means required
- All arrays are empty by default
- All non-required numbers are 0 by default

**Comment by gsc2001** [comment]
dependent on #1 #2

**Comment by gsc2001** [comment]
I think the product should be manyTomany Field

**Comment by gsc2001** [comment]
i suggest basically many to one relationship between order and user
```python
class Order:
    user = model.ForeignKey
    products = model.ManyToManyField(Product, through='OrderObj')
    status = enum()
```
